version: '3.9'
services:
  rust:
    build:
      context: docker/rust
    image: rust-build:latest
    volumes:
      - ./:/app
    working_dir: /app
    user: root:root
    command:
      - cargo
      - build
  mysql:
    image: mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/data
  redis:
    image: redis
    ports:
      - "6379:6379"
volumes:
  mysql_data:
