### get state
GET http://localhost:8080/state

### post format form-data
POST http://localhost:8080/post/form-data
Content-Type: application/x-www-form-urlencoded

username=yanlongli&password=123

### post format json
POST http://localhost:8080/post/json
Content-Type: application/json

{
  "username": "yanlongli",
  "password": "456"
}

### put
PUT http://localhost:8080/put22
Content-Type: application/json

###
GET http://localhost:8080/users/test
Content-Type: application/json

###
GET http://localhost:8080/users
Content-Type: application/json

###
POST http://localhost:8080/users
Content-Type: application/json

{
  "username": "测试",
  "password": "123"
}
### delete user test
DELETE http://localhost:8080/users/test
Content-Type: application/json

###11
GET http://localhost:8080/static/index.html

###
WEBSOCKET ws://localhost:8080/ws

###
GET http://localhost:8080/redis
###
